print("How to make easy mac")
print("grab a medium sized pot")
print("Bring the pot over to the sink")
print("Turn on the sink")
print("Fill the pot about half way with water")
print("Bring the pot over to the stove")
print("Place the pot of water onto the stove")
print("Turn on the burner under the pot of water to max heat")
print("Cover the pot with a lid")
print("Wait for the water to come to a boil")
print("Remove lid off of pot")
print("Reduce heat to maintain a slow boil")
print("Open box of 'easy mac'")
print("remove cheese pouch from inside the box")
print("Set cheese pouch aside for later")
print("Pick up the box of noodles")
print("Add noodles to water")
print("wait five minutes for noodles to cook")
print("Put a strainer in the sink")
print("remove pot from the stove")
print("Bring pot over to the sink")
print("pour contents of the pot into the strainer")
print("Pour the contents of the strainer back into the pot")
print("Grab the pouch of cheese powder")
print("Tear of the top portion of the pouch")
print("Pour the contents of the pouch into the pot")
print("Grab a fork")
print("Stir together the contents in the pot")
